spring:
  datasource:
    #url: jdbc:mysql://192.168.10.81:3306/peaje
    url: jdbc:mysql://localhost:3306/peaje #dev
    username: root
    #password: P@ssw0rd #Prdo
    password: desarrollo #dev
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl # Respeta las mayusculas en nombre de tabla
