spring:
  datasource:
    url: jdbc:mysql://localhost:3306/peaje
    username: apiuser
    password: desarrollo
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl # Respeta las mayusculas en nombre de tabla
